name: 'contribflow'
version: '1.0.0'
config-version: 2

profile: 'contribflow'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  contribflow:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

